### ISSUE TITLE
symm-mh.clab.yml: ifreload isn't triggered on server nodes

### ISSUE THREAD

**Issue by dteslya** [hellt/clabs#8]
Hi!

I try to deploy `symm-mh.clab.yml` topology and all hosts do not get their interfaces configured. After some digging, I found out that the entrypoint script waits for 3 more interfaces to come up aside from eth0. But according to the topology each server has only 2 uplinks to the leaf switches. Changing `cmd: 3` to `cmd: 2` under the server definition in the topology file seems to fix this issue.

**Comment by hellt** [comment]
Hi,
I think @networkop who is the author of this can comment on that 
I remember something like that was fixed for another lab

**Comment by networkop** [comment]
hey @dteslya can you check if the hosts have `CLAB_ENV_INTFS` env variable configured inside their shell? 
Containerlab will automatically inject this env var and make it equal to the expected number of interfaces and hosts image should pick it up [automatically](https://github.com/networkop/cx/blob/main/host/entrypoint.sh#L3).

I think `cmd` field may need to be removed completely to make it work? can you try that?

**Comment by dteslya** [comment]
Yes, removing the `cmd` field also worked. And the `CLAB_INTFS` env variable is injected.

```
$ docker exec clab-citc-server01 bash -c 'echo "$CLAB_INTFS"'
2
```

**Comment by networkop** [comment]
ok, thanks. I'll do a PR to remove `cmd` shortly.

**Comment by dteslya** [comment]
Thank you! Btw, `symm-mh.clab.yml` has the same issue. Removing `cmd` also helps there.

**Comment by hellt** [comment]
The pr has been merged #9

**Comment by networkop** [comment]
thanks. closing the issue.

**Comment by networkop** [comment]
🤣  forgot it's not my issue

**Comment by dteslya** [comment]
thank you!
